version: '3.7'

services:
  nginx:
    container_name: my_nginx
    build: ./requirements/nginx/
    image: nginx:42
    ports: # 호스트 443번을 컨테이너 443에 연결
      - "443:443"
    volumes:
      - wp_data:/var/www/wordpress
    env_file:
      - .env
    restart: always
    networks:
      - inception
    depends_on:
      - wordpress

  wordpress:
    container_name: my_wordpress
    build: ./requirements/wordpress/
    image: wordpress:42
    volumes:
      - wp_data:/var/www/wordpress
    env_file:
      - .env
    restart: always
    networks:
      - inception
    depends_on:
      - mariadb

  mariadb:
    container_name: my_mariadb
    # image와 build 키워드를 docker-compose에서 동시에 사용하면 image를 레지스트리에서 찾지 않고 build에서 만든 것을
    # image로 사용하고 이름과 태그를 image키워드 옆에있는 mairadb 42로 정해버린다.
    build: ./requirements/mariadb/
    image: mariadb:42
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    restart: always
    networks:
      - inception

networks:
  inception:
    name: inception

volumes:
  wp_data:
    name: wp
    driver: local
    driver_opts:
      device: /home/minsuki2/data/WordPress
      o: bind       # 마운트 옵션 bind하겠다.
      type: none    # none으로 해야 그대로 bind됨
  db_data:
    name: db
    driver: local
    driver_opts:
      device: /home/minsuki2/data/DB
      o: bind
      type: none

