version: '3.7'

services:
  nginx:
    container_name: my_nginx
    build: ./requirements/nginx/
    image: nginx:42
    volumes:
      - wp_data:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "443:443"
    init: true
    restart: always

  wordpress:
    container_name: my_wordpress
    build: ./requirements/wordpress/
    image: wordpress:42
    volumes:
      - wp_data:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb
    init: true
    restart: always

  mariadb:
    container_name: my_mariadb
    build: ./requirements/mariadb/
    image: mariadb:42
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    init: true
    restart: always

networks:
  inception:
    name: inception

volumes:
  wp_data:
    name: wp
    driver: local
    driver_opts:
      type: none
      device: /home/minsuki2/data/WordPress
      o: bind
  db_data:
    name: db
    driver: local
    driver_opts:
      type: none
      device: /home/minsuki2/data/DB
      o: bind

