version: '3.7'

services:
  nginx:
    container_name: my_nginx
    build: ./requirements/nginx/
    image: nginx:42
    ports: # 호스트 443번을 컨테이너 443에 연결
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env
    restart: always
    depends_on:
      - wordpress

  wordpress:
    container_name: my_wordpress
    build: ./requirements/wordpress/
    image: wordpress:42
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    env_file:
      - .env
    tty: true
    restart: always
    depends_on:
      - mariadb

  mariadb:
    container_name: my_mariadb
    # image와 build 키워드를 docker-compose에서 동시에 사용하면 image를 레지스트리에서 찾지 않고 build에서 만든 것을
    # image로 사용하고 이름과 태그를 image키워드 옆에있는 mairadb 42로 정해버린다.
    build: ./requirements/mariadb/
    image: mariadb:42
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always


networks:
  inception:
    name: inception

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /goinfre/minsuki2/inception_data/wordpress
      o: bind       # 마운트 옵션 bind하겠다.
      type: none    # none으로 해야 그대로 bind됨
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /goinfre/minsuki2/inception_data/mariadb
      o: bind
      type: none

