version: '3'
services:
  webserver:
    container_name: my_nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - wp_data:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - database
      - wordpress_php
  wordpress_php:
    container_name: my_wordpress
    image: wordpress:php8.2-fpm
    volumes:
      - wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: test123 
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - database
  database:
    container_name: my_database
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: wordpress
volumes:
  db_data:
  wp_data:

