version: '3'
services:
  web:
    container_name: my_nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php
  php:
    container_name: my_php
    image: php:fpm
    volumes:
      - ./html:/var/www/html

